#!/usr/bin/env python

import recognize_speech as rs
import rospy


def main():
    name_list = ["jessica", "allison", "fred", "jeff", "brian", "ashley"]
    drink_list = ["water", "punch", "root beer"]
    speech = rs.Speech()
    result_name = None
    result_drink = None
    print("Can you please provide your name and drink?")
    tries = 5
    remaining = tries
    while (result_name is None or result_drink is None) and remaining != 0:
        if tries != remaining:
            if result_name is None and result_drink is None:
                print("Sorry I didnt quite catch that")
            elif result_name is None:
                print("Can you please repeat your name")
            elif result_drink is None:
                print("Can you please repeat your favorite drink")
        text = speech.recognizeGoogle()
        lower_text = text.lower()
        if result_name is None:
            for name in name_list:
                if name.lower() in lower_text:
                    result_name = name
                    break

        if result_drink is None:
            for drink in drink_list:
                if drink.lower() in lower_text:
                    result_drink = drink
                    break
        remaining -= 1
    # bad path, robot failed to recognize speech
    if result_name is None or result_drink is None:
        return None
    # good path, robot recognized name and drink
    result = (result_name, result_drink)
    print("Hi, " + result[0] + " let me get you a " + result[1])
    return result
    rospy.spin()


if __name__ == '__main__':
    main()
